#Base method/path
/: 
  controller: Base
  action: index

#Auth method/path
/signup:
  controller: Auth
  action: renderSignup

/login:
  controller: Auth
  action: renderLogin

/addUser:
  controller: Auth
  action: signup

/signinUser:
  controller: Auth
  action: signin

/updateUser:
  controller: Auth
  action: updateUser

/logout:
  controller: Auth
  action: logout

/deleteUser:
  controller: Auth
  action: deleteUser

/profil:
  controller: Auth
  action: renderProfil

/dashboard:
  controller: Auth
  action: renderDashboard

/users:
  controller: Auth
  action: renderUsers

/resetPassword:
  controller: Auth
  action: renderResetPassword

/modifyPassword:
  controller: Auth
  action: renderModifyPassword

/updatePassword:
  controller: Auth
  action: updatePassword

/activation:
  controller: EmailVerification
  action: activateAccount

/sendNewPassword:
  controller: EmailVerification
  action: sendResetPwdMail

/createUser:
  controller: Auth
  action: createUser

/signinUser:
  controller: Auth
  action: signin


/admin/pages:
  controller: AdminPages
  action: index

/admin/pages/create:
  controller: AdminPages
  action: createForm

/admin/pages/edit:
  controller: AdminPages
  action: editForm

/admin/pages/delete:
  controller: AdminPages
  action: delete

/admin/pages/create-submit:
  controller: AdminPages
  action: create

/admin/pages/edit-submit:
  controller: AdminPages
  action: edit
