#Base method/path
/:
  controller: Base
  action: index


#Auth method/path
/signup:
  controller: Auth
  action: renderSignup

/login: 
  controller: Auth
  action: renderLogin

/addUser: 
  controller: Auth
  action: signup

/createUser:
  controller: Auth
  action: createUser

/signinUser:
  controller: Auth
  action: signin